version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: hospitales
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data


# Servicio para PgAdmin
  pgadmin:
    image: dpage/pgadmin4:7.5
    container_name: my_pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
    - "5050:80"
